# Generated by Django 6.0 on 2025-12-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invitationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-year', '-month', '-upload_date']},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=set(),
        ),
    ]
