# Generated by Django 6.0.1 on 2026-01-19 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_payslip_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the evaluated month')),
                ('savings_rate_score', models.IntegerField()),
                ('fixed_expenses_score', models.IntegerField()),
                ('budget_adherence_score', models.IntegerField()),
                ('trend_score', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('overall_status', models.CharField(choices=[('red', 'Necesita Atención'), ('yellow', 'Regular'), ('green', 'Excelente')], max_length=10)),
                ('cached_advice', models.TextField(blank=True, null=True)),
                ('advice_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_score_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_score_snapshots',
                'ordering': ['-month'],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
